import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider'
import PizzaList from '../components/PizzaList'


export default function Home({ pizzaList}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Slider></Slider>
      <PizzaList pizzaList={pizzaList}></PizzaList>
    </div>
  )
}

