import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider'
import PizzaList from '../components/PizzaList'
import AddButton from '../components/AddButton'
import axios from 'axios'


export default function Home({ pizzaList, admin }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Slider></Slider>
      {admin && <AddButton></AddButton>}
      <PizzaList pizzaList={pizzaList}></PizzaList>
    </div>
  )
}

export const getServerSideProps = async (ctx) => {

  console.log(ctx)
  const myCookie = ctx.req?.cookies || ""

  let admin = false

  if (myCookie.token !== process.env.REACT_APP_TOKEN) {
    admin = false
  }
  else {
    admin = true
  }

  const res = await axios.get("http://localhost:3000/api/products")
  return {
    props: {
      pizzaList: res.data, admin
    }
  }

}
